version: "3.9"

services:
  web:
    build: .
    working_dir: /app/menswear
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_DEBUG=1
    restart: unless-stopped
